version: "3.8"

services:
  client:
    container_name: pz-frontend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    env_file:
      - .env
